### PR TITLE
correct misleading/wrong documentation for pool ranges

### PR DESCRIPTION
**Pull request by dwerder**

### CODE REVIEW

**Comment by dwerder** [comment]
Tests are failing because of rake version >=11.0.0. Should be fixed in the Gemfile

**Comment by bastelfreak** [comment]
Hi @dwerder, thanks for the PR! Please merge master into your branch, this should fix the errors.

**Comment by jyaworski** [comment]
Ping @dwerder

**Comment by dwerder** [comment]
@jyaworski I reopen the PR with updated master.

**Pull request closed without merging**
