### PR TITLE
Support SmartOS

### PR DESCRIPTION
**Pull request by joelgarboden**
Add support for [Joyent SmartOS](https://www.joyent.com/smartos)

Functional on SmartOS base-64 15.4.1-lts

### CODE REVIEW

**Comment by joelgarboden** [comment]
Using this manifest, with JSON Hiera

```
class dhcp_server (
    $interfaces = [ 'net0' ],
    $nameservers = [ '10.70.7.2', '10.70.7.3' ],
    $ntpservers = ['us.pool.ntp.org'],
    $dnssearchdomains = [ $::domain ],
    $dnsdomain = [ $::domain ],
    $pools = [],
    $hosts = []
  ) {

  class { 'dhcp':
    service_ensure => running,
    dnsdomain => $dnsdomain,
    nameservers => $nameservers,
    ntpservers => $ntpservers,
    interfaces => $interfaces,
    dnssearchdomains => $dnssearchdomains,
  }

  define dhcp_server::dhcp_pool($pool_data = $title) {
    dhcp::pool{ $pool_data['description']:
      network => $pool_data['network'],
      mask    => $pool_data['mask'],
      range   => $pool_data['range'],
      gateway => $pool_data['gateway'],
    }
  }

  define dhcp_server::host_reservation($host_data = $title) {
    dhcp::host{ $host_data['description']:
      mac => $host_data['mac'],
      ip => $host_data['ip'],
    }
  }

  dhcp_server::dhcp_pool { $pools: }

  dhcp_server::host_reservation { $hosts: }

}
```

**Comment by juniorsysadmin** [comment]
@joelgarboden If you could add some corresponding tests in spec/ that would be super

**Comment by bastelfreak** [comment]
*push*

@joelgarboden can you please add spec tests?

**Comment by joelgarboden** [comment]
Adding spec tests is a bit unclear to me, I don't see any obvious templates or documentation in modulesync repos. It looks like Vagrant has some SmartOS support, but not sure how to get that into something your modulesync repo wants.

**Comment by bastelfreak** [comment]
yep, sorry for being so unspecific. Thanks for the clarification @ekohl.

**Comment by petems** [comment]
Tests added in rebase: https://github.com/voxpupuli/puppet-dhcp/pull/131, closing in favour of 👍

**Pull request closed without merging**
